compiler:
 - gcc

language: cpp
sudo: required
dist: xenial
osx_image: xcode8.3

os: osx
  env:
    - BUILD_INSTALL_GTEST=YES
    

branches:
  only:
    - master
    - develop
    - package
    - /drv_.*$/
    - travis
    - refactor/unittest
    - feature/travisosx

before_install:
    - echo Install dependencies
    - CI/travis/deps-${TRAVIS_OS_NAME}.sh

install:
    - echo Building INDI Core and drivers
    - CI/travis/build-core.sh

script:
    - CI/travis/run-tests.sh 

